var updateURL = "https://raw.githubusercontent.com/fuzzyframecanon/PetitePiluleRouge/master/config.json";

var localBackup = {
    "Monde(?! [Dd]iplo)(?:\\.fr)?": ["Xavier Niel", "Pierre Berge", "Matthieu Pigasse"],
    "Huffington Post": ["Xavier Niel", "Pierre Berge", "Matthieu Pigasse"],
    "Courrier International": ["Xavier Niel", "Pierre Berge", "Matthieu Pigasse"],
    "([Ll]'Obs|Nouvel Observateur)": ["Xavier Niel", "Pierre Berge", "Matthieu Pigasse"],
    "Télérama": ["Xavier Niel", "Pierre Berge", "Matthieu Pigasse"],
    "In[Rr]ocks": ["Matthieu Pigasse"],
    "Nova": ["Matthieu Pigasse"],
    "Vice": ["Matthieu Pigasse"],
    "Challenges(?:\\.fr)?": ["Claude Perdriel"],
    "[Ll]'Opinion": ["Claude Perdriel", "Famille Bettencourt", "Nicolas Beytout", "Bernard Arnault"],
    "(?:[Ll]e)?Parisien(?:\\.fr)?": ["Bernard Arnault"],
    "Échos": ["Bernard Arnault"],
    "Lib[eé]ration(?:\\.fr)?": ["Patrick Drahi", "Alain Weil"],
    "[Ll]'Express": ["Patrick Drahi", "Alain Weil"],
    "BFMTV(?:\\.(?:COM|com))?": ["Alain Weil", "Pascal Houzelot"],
    "VSD": ["Famille Mohn"],
    "Capital(?:\\.fr)?": ["Famille Mohn"],
    "M6": ["Famille Mohn"],
    "W9": ["Famille Mohn"],
    "RTL(?:\\.(?:FR|fr))?": ["Famille Mohn"],
    "Europe1": ["Arnaud Lagardere", "Quatar Investment Authority"],
    "Paris Match": ["Arnaud Lagardere", "Quatar Investment Authority"],
    "(JDD|Journal du Dimanche)": ["Arnaud Lagardere", "Quatar Investment Authority"],
    "Marianne": ["Yves de Chaisemartin"],
    "[Ll]a Dépêche": ["Famille Baylet"],
    "Ouest-France": ["Famille Hutin"],
    "[Ll]a Voix du Nord": ["Famille Hurbain", "Credit Agricole"],
    "Télégramme": ["Edouard Coudurier"],
    "Nice-Matin": ["Nethys"],
    "Var-Matin": ["Nethys"],
    "[Ll]a Provence": ["Bernard Tapie", "Nethys"],
    "Corse Matin": ["Bernard Tapie", "Nethys"],
    "France-Antilles": ["Philippe Hersant"],
    "France-Guyane": ["Philippe Hersant"],
    "Charente Libre": ["Famille Lemoine"],
    "Sud Ouest": ["Famille Lemoine"],
    "[Ll]'Est Républicain": ["Credit Mutuel"],
    "Dauphiné [Ll]ibéré": ["Credit Mutuel"],
    "Arte": ["Republique francaise", "Republique federale d'Allemagne"],
    "Notre Temps": ["Les Augustins de l'Assomption"],
    "[Ll]a Croix": ["Les Augustins de l'Assomption"],
    "Point(?:\\.fr)?": ["Francois Pinault"],
    "TF1": ["Famille Bouygues"],
    "LCI": ["Famille Bouygues"],
    "Slate": ["Benjamin de Rothschild", "Financiere Viveris"],
    "Canal(?: ?\\+| ?Plus)": ["Vincent Bollore"],
    "iTélé": ["Vincent Bollore"],
    "Direct Matin": ["Vincent Bollore"],
    "C8": ["Vincent Bollore"],
    "Figaro(?:\\.fr)?": ["Famille Dassault"],
    "20(?:m| M)inutes(?:\\.fr)?": ["Famille Hutin", "Credit Agricole"],
    "La Tribune(?:\\.fr)?": ["Jean-Christophe Tortora", "Laurent Alexandre"],
    "[Ll]'Équipe(?:\\.fr)?": ["Famille Amaury"],
    "Eurosport(?:\\.fr)?" : ["Famille Bouygues"],
    "Pure People": ["Marc de Lacharrière"],
    "Boursorama(?:\\.com)?": ["Société Générale"],
    "(RFI|Radio France Internationale)": ["Republique Francaise"],
    "France ?[Ii]nter": ["Republique Francaise"],
    "France(?:info| Info)": ["Republique Francaise"],
    "France Bleu": ["Republique Francaise"],
    "France ?24": ["Republique Francaise"],
    "France Culture": ["Republique Francaise"],
    "Public Sénat": ["Republique Francaise"]
};
